get http://localhost:3000

###
get http://localhost:3000/add-product

###
get http://localhost:3000/fajlfdsjk


###
post http://localhost:3000/admin/product
Content-Type: application/json

{
    "title": " more test"
}

